### ISSUE TITLE
Google Maps is stuk

### ISSUE THREAD

**Issue by qurben** [csrdelft/csrdelft.nl#116]

**Comment by qurben** [comment]
Op de woonoorden pagina, als je op twee verschillende plekken op 'Meer lezen...' klikt

**Comment by brussee** [comment]
Er wordt nu ook met de v2 en v3 van de google maps api gewerkt op de stek. Ik dacht zelfs te zien dat bbcode [locatie] v2 is en bbcode [map] v3.

**Comment by brussee** [comment]
Google Maps API warning: NoApiKeys https://developers.google.com/maps/documentation/javascript/error-messages#no-api-keys

Control is no longer supported in the Google Maps Javascript API v2. Please visit https://developers.google.com/maps/documentation/javascript/v2/v2tov3 to migrate your application to v3.
Map.addControl is no longer supported in the Google Maps Javascript API v2. Please visit https://developers.google.com/maps/documentation/javascript/v2/v2tov3 to migrate your application to v3.

**Comment by thervh70** [comment]
@brussee @qurben dit is gefixt toch?

**Comment by brussee** [comment]
@thervh70 Door wie en in welke commit / PR dan?

**Comment by brussee** [comment]
In de console van Chrome zie ik het volgende: https://csrdelft.nl/forum/reactie/110091#110091

110091#110091:1 Refused to execute script from 'https://csrdelft.nl/layout/js/gmaps.js' because its MIME type ('text/html') is not executable, and strict MIME type checking is enabled.

https://csi.gstatic.com/csi?v=2&s=mapsapi3&v3v=26.8&action=apiboot2&libraries=adsense%2Cgeometry%2Czombie&e=10_1_0,10_2_0&rt=main.6 Failed to load resource: net::ERR_BLOCKED_BY_CLIENT

110091:965 Uncaught ReferenceError: loadGmaps is not defined(…)

util.js:208 Google Maps API warning: NoApiKeys https://developers.google.com/maps/documentation/javascript/error-messages#no-api-keys
